/* Palette generated by Material Palette - materialpalette.com/teal/cyan */

// .dark-primary-color    { background: #00796B; }
// .default-primary-color { background: #009688; }
// .light-primary-color   { background: #B2DFDB; }
// .text-primary-color    { color: #FFFFFF; }
// .accent-color          { background: #00BCD4; }
// .primary-text-color    { color: #212121; }
// .secondary-text-color  { color: #757575; }
// .divider-color         { border-color: #BDBDBD; }
module.exports = {
	defaultBackgroundColor: '#e9e9ef',
	defaultBackgroundColor2: '#efeff6',
	darkPrimaryColor: '#2980B9',
	defaultPrimaryColor: '#3498DB',
	lightPrimaryColor: '#67ACDB',
	textPrimaryColor: '#2C3E50',
	accentColor: '#FFD400',
	primaryTextColor: '#2C3E50',
	secondaryTextColor: '#b1b1b1',
	dividerColor: '#cccccc',

	thirdTextColor: '#6e6e6e',
	// talk
	talkBackgroundColor: 'white',
	talkMeMessageColor: '#5EBDFF',
	talkYouMessageColor: '#e9e9ef',

	fontSmall: 10,
	fontMediumSmall: 12,
	fontMedium: 14,
	fontMediumLarge: 16,
	fontLarge: 18,
}
