# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WhoClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for WhoClient

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'WhoClientTests' do
	inherit! :search_paths
	# Pods for testing
  end

end
